portfoy:
  "DSTKF.IS": 0.2285
  "OZATD.IS": 0.1430
  "PEKGY.IS": 0.0773
  "TEHOL.IS": 0.0714
  "TERA.IS:   0.0663
  "TRHOL.IS": 0.0561
  "ANELE.IS": 0.0199
  "SELEC.IS": 0.0104
  "ALKLC.IS": 0.0054
  "SVGYO.IS": 0.0052
  "HEDEF.IS": 0.0027
  "MANAS.IS": 0.0014
  "DAPGM.IS": 0.0007
  "TMPOL.IS": 0.0001
  "EUPWR.IS": 0.0001

benchmarks:
  "BIST 100": "XU100.IS"
  "ALTIN": "GC=F"
  "DOLAR": "USDTRY=X"
  "BIST BANKA": "XBANK.IS"
