name: Borsa Takip Botu

on:
  schedule:
    # Saat 09:00 ile 16:00 arası her saat başı (TSİ 11:00 - 18:00)
    - cron: '12 14 * * 1-5'
    # Saat 16:00'da (TSİ 19:00) tek seferlik Özet Modu
    - cron: '0 16 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Bot
        run: python borsa_bot.py
