telegram:
  token: "8985851282:AAHz4O3Ygyp9herlBfq0JSRG3Ps3tGFxVZ8"
  chat_id: "1402340669"

portfoy:
  "DSTKF.IS": 0.1771
  "OZATD.IS": 0.1716
  "UKA.IS":   0.1284
  "TERA.IS":  0.1150
  "PEKGY.IS": 0.0989
  "TRHOL.IS": 0.0659
  "TEHOL.IS": 0.0550
  "ANELE.IS": 0.0215
  "HMV.IS":   0.0120
  "ALKLC.IS": 0.0066
  "SVGYO.IS": 0.0055
  "TMPOL.IS": 0.0033
  "HEDEF.IS": 0.0028
  "EUPWR.IS": 0.0003
  "CWENE.IS": 0.0003
  "T3B.IS":   0.0002

benchmarks:
  "BIST 100": "XU100.IS"
  "ALTIN": "GC=F"
  "DOLAR": "USDTRY=X"
  "BIST BANKA": "XBANK.IS"
