name: Borsa Takip Botu

on:
  schedule:
    # TSİ 11:25 - 18:25 arası her saat başının 25. dakikasında çalışır (Hafta içi)
    - cron: '30 17 * * 1-5'
      timezone: 'Europe/Istanbul'

    # TSİ 19:00'da Özet Modu olarak tek seferlik çalışır (Hafta içi)
    - cron: '0 19 * * 1-5'
      timezone: 'Europe/Istanbul'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Bot
        run: python borsa_bot.py
