name: Borsa Takip Botu

on:
  schedule:
    # Her saat başı çalışır (00:00, 01:00, 02:00...)
    - cron: '0 * * * *' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Gerekli Kütüphaneleri Yükle
        run: |
          pip install yfinance pandas_market_calendars requests

      - name: Kodu Çalıştır
        run: python borsa_bot.py
